### ISSUE TITLE
refit of gsfTracks

### ISSUE THREAD

**Issue by amartelli** [CMSBParking/BParkingNANO#11]
amartelli:gsfTransientTrack  
is a branch in 10_2_15 with the new TransientTrack builder for gsfTracks, where the Mode() covariance matrix is used

to use this, use the "buildfromGSF" constructor of the TransientTrackBuilder
example here:
with 
edm::ESHandle<TransientTrackBuilder> theTTBuilder;
 iSetup.get<TransientTrackRecord>().get("TransientTrackBuilder",theTTBuilder);

can use the new constructor as: 
 leptonTTgsf = theTTBuilder->buildfromGSF(ele.gsfTrack());

"fake constructor" that despite the name accesses the kfTrack parameter:
leptonTTtrack = theTTBuilder->build(ele.gsfTrack());

(will try to have this integrated in cmssw or blessed by egamma/tracking pog once back from holiday)

**Comment by sarafiorendi** [comment]
ciao,
I made a quick test using current master (+ one line modification) + Arabella's branch for gsfTracks and everything works fine. 
How do we want to proceed? Add to the instructions of this framework to also checkout the changes from Arabella's branch (4 files basically)? Or add a cmssw repo to this organisation containing the necessary changes to use the updated gsf tt builder? Other options?

**Comment by mverzett** [comment]
I would add a branch in our [shared cmssw fork](https://github.com/CMSBParking/cmssw) and then make the changes needed in our repo (README and code)

**Comment by mverzett** [comment]
As the relative PR is merged I close the issue
