### ISSUE TITLE
Runing on crab

### ISSUE THREAD

**Issue by mverzett** [CMSBParking/BParkingNANO#40]
Hi @all,

It's about time to enable running on crab. As I imagine everyone has its favourite way. This is just to start the discussion.

I recently came across this system that I find quite sleek and effective: all the samples are kept in a [yaml file](https://github.com/HNLto2L2Q/HNL/blob/run_2018/HeavyNeutralLeptonAnalysis/test/input_data_2018.yml) and the submission is handled by a [python script](https://github.com/HNLto2L2Q/HNL/blob/run_2018/HeavyNeutralLeptonAnalysis/test/crab_data_2018.py)

Any other solution any of you would like to propose?

**Comment by sarafiorendi** [comment]
ok, I'm using a very similar python one, so ok starting from this for me.

**Comment by amartelli** [comment]
yes me too,  the python contains the standard config that I used to use
Fine with this

**Comment by mverzett** [comment]
First implementation is available for comments in #41
