### ISSUE TITLE
update data GT

### ISSUE THREAD

**Issue by sarafiorendi** [CMSBParking/BParkingNANO#43]
From [twiki](https://twiki.cern.ch/twiki/bin/viewauth/CMS/PdmVAnalysisSummaryTable)
we should have:
ABC: 102X_dataRun2_v11
D: 102X_dataRun2_Prompt_v14

Once we are happy with the crab cfg we can add there the option to use the appropriate GT.

**Comment by mverzett** [comment]
Adressed in #41

**Comment by mverzett** [comment]
As #41 is merged I close the issue
