### ISSUE TITLE
why are we printing this out? is it needed later or is a forgoten flag?

### ISSUE THREAD

**Issue by gkaratha** [CMSBParking/BParkingNANO#8]
https://github.com/CMSBParking/BParkingNANO/blob/98cb170ae9875e9e20083133782fe894a9c5ab74/BParkingNano/plugins/ElectronMerger.cc#L74

**Comment by amartelli** [comment]
it's forgotten, I already fixed and will commit. Thanks for checking

**Comment by gkaratha** [comment]
Thanks for the quick response !
